// <auto-generated />
using AlesyaTheTraveller.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlesyaTheTraveller.Migrations
{
    [DbContext(typeof(CorvegaContext))]
    partial class CorvegaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlesyaTheTraveller.Entities.Responses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnName("active");

                    b.Property<int>("Respid")
                        .HasColumnName("respid");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnName("word")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("Respid");

                    b.ToTable("responses");
                });

            modelBuilder.Entity("AlesyaTheTraveller.Entities.Sorting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnName("active");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnName("type")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int>("Typeid")
                        .HasColumnName("typeid");

                    b.Property<string>("Typename")
                        .HasColumnName("typename")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("Type", "Typeid")
                        .IsUnique()
                        .HasName("UC_OneTypeTypeid");

                    b.ToTable("sorting");
                });

            modelBuilder.Entity("AlesyaTheTraveller.Entities.Utterances", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnName("content")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<int>("Respid")
                        .HasColumnName("respid");

                    b.HasKey("Id");

                    b.HasIndex("Respid")
                        .IsUnique()
                        .HasName("UQ__utteranc__2C2806A0EA17A916");

                    b.ToTable("utterances");
                });

            modelBuilder.Entity("AlesyaTheTraveller.Entities.Responses", b =>
                {
                    b.HasOne("AlesyaTheTraveller.Entities.Utterances", "Resp")
                        .WithMany("Responses")
                        .HasForeignKey("Respid")
                        .HasConstraintName("FK__responses__activ__52593CB8")
                        .HasPrincipalKey("Respid");
                });
#pragma warning restore 612, 618
        }
    }
}
